<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [10]:
import numpy as np

lista= [0,1,2,3,4,5,6,7,8,9]

array1D0_9=np.array(lista)
array1D0_9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [12]:
array2D0_9= array1D0_9.reshape(2,5)
array2D0_9

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [13]:
np.where(array2D0_9 != 0)  #El primer array es la fila y el segundo la columna (porque es bidireccional (si fuera tri el primero matriz, fila y columna))

(array([0, 0, 0, 0, 1, 1, 1, 1, 1]), array([1, 2, 3, 4, 0, 1, 2, 3, 4]))

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [41]:
np.random.randint(0, 2, (3,3))

array([[1, 0, 0],
       [1, 1, 0],
       [1, 0, 0]], dtype=int32)

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [51]:
np.random.randint(0, 21, 10 ).max()

np.int32(19)

#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [ ]:
unidim= np.array([1,2,3,4,5,6,7,8,9,10])  #Como es unidimensional solo tiene fila (ni columna ni matriz)
unidim[: : -1]   #Al poner -1 (En salto) hace que vaya desde el último al primero


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [101]:
lista= [[[1,2,3,4],[5,6,7,8],[9,10,11,12],],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]
array_3d= np.array(lista)
print(array_3d)

print(array_3d[1, 0, 2])

print(array_3d[0, :, :])

print(array_3d[1, 2, :])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
15
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[21 22 23 24]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [114]:
array3DD= np.random.randint(1,30, (3,2,5))
print(array3DD)

print(array3DD[:,0,1])

print(array3DD[1:, :, :])

[[[ 3 11 12 25  1]
  [21 20 19  3 18]]

 [[ 1 14  8 19  2]
  [14  1  1  2 24]]

 [[26  4 26 14 14]
  [23 13 13  9  1]]]
[11 14  4]
[[[ 1 14  8 19  2]
  [14  1  1  2 24]]

 [[26  4 26 14 14]
  [23 13 13  9  1]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [128]:
array_3_D= np.random.randint(1,24, (4,3,2))
print(array_3_D)
array_3_D[1, 1, :] = 0
array_3_D[3, :, :] = -1
print(array_3_D)

[[[ 4 17]
  [16 14]
  [22 13]]

 [[ 1 16]
  [22 16]
  [12  6]]

 [[19  6]
  [19 22]
  [16  9]]

 [[22 23]
  [11  3]
  [20  5]]]
[[[ 4 17]
  [16 14]
  [22 13]]

 [[ 1 16]
  [ 0  0]
  [12  6]]

 [[19  6]
  [19 22]
  [16  9]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [140]:
otro3D= np.random.randint(-10, 13, (2,4,3))
print(f'\n{otro3D}')             #Recuerda que hace falta la f para añadir espacios
print(f"\n{otro3D[otro3D > 5]}")
otro3D[otro3D < 0] = 0
print(f'\n{otro3D}')


[[[-10   7   6]
  [ 10 -10 -10]
  [ -4  12  -9]
  [ -7  -2   5]]

 [[  4  -3  -6]
  [ -7  -4  -8]
  [  3  -9   8]
  [  1   4   8]]]

[ 7  6 10 12  8  8]

[[[ 0  7  6]
  [10  0  0]
  [ 0 12  0]
  [ 0  0  5]]

 [[ 4  0  0]
  [ 0  0  0]
  [ 3  0  8]
  [ 1  4  8]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [152]:
otro3d= np.random.randint(1, 27, (3,3,3))
print(f"\n{otro3d}")
print(f"\n{otro3d[1, :, :2]}")

tercer_array= otro3d[2, :, :]
tercer_array[tercer_array > 20]



[[[ 3 11  6]
  [ 6 13 14]
  [ 4 15 22]]

 [[25 19 14]
  [13  6 23]
  [ 5 17  6]]

 [[23 24  3]
  [23  9 18]
  [26  6  5]]]

[[25 19]
 [13  6]
 [ 5 17]]


array([23, 24, 23, 26], dtype=int32)

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [210]:
numeros10= np.random.randint(1,30, 10)
print(numeros10)
min= numeros10[numeros10 == numeros10.min()] = 0
max= numeros10[numeros10 == numeros10.max()] = 0

numeros10[ (numeros10 == min) & (numeros10 == max)]
print(numeros10)


[ 7  2  8  8 28  7 28  6  4  6]
[7 0 8 8 0 7 0 6 4 6]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [196]:
quince= np.sort(np.random.randint(1,100, 15))
quince

array([ 3, 11, 18, 31, 35, 35, 36, 37, 39, 63, 75, 91, 94, 99, 99],
      dtype=int32)

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [205]:
matriz1= np.random.randint(1,10, (4,4))
suma= np.sum(matriz1)
suma

np.int64(74)

#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [217]:
matriz1= np.sort(np.random.randint(1,10, (5,5)))

matriz1[:, 0] = 1
matriz1[:, 4] = 1

print(matriz1)

[[1 6 6 6 1]
 [1 4 4 7 1]
 [1 4 4 5 1]
 [1 2 3 3 1]
 [1 2 3 6 1]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [226]:
media_desv= np.random.randint(1,20, 10)
print(np.mean(media_desv))
print(np.std(media_desv).round(2))

12.1
6.35


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [229]:
array_normal= np.random.randint(1,24, (2,3,4))
print(array_normal)
np.transpose(array_normal, (2, 1, 0 )) 

[[[ 9 22  1  2]
  [ 3 12 18 14]
  [13 20  1 13]]

 [[ 5  2  7 22]
  [21 12 12 12]
  [ 1 21  7 11]]]


array([[[ 9,  5],
        [ 3, 21],
        [13,  1]],

       [[22,  2],
        [12, 12],
        [20, 21]],

       [[ 1,  7],
        [18, 12],
        [ 1,  7]],

       [[ 2, 22],
        [14, 12],
        [13, 11]]], dtype=int32)

Lo que ha pasado es que se han hecho tantas matrices como columnas había y se han hecho tantas columnas como matrices había.

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [230]:
array_normal= np.random.randint(1,24, (3,4,2))
print(array_normal)
np.transpose(array_normal, (1, 0, 2 )) 

[[[ 9  5]
  [16 22]
  [15 21]
  [16  2]]

 [[12  9]
  [10 12]
  [17 11]
  [21  2]]

 [[15  6]
  [ 1  3]
  [ 1  8]
  [ 7 17]]]


array([[[ 9,  5],
        [12,  9],
        [15,  6]],

       [[16, 22],
        [10, 12],
        [ 1,  3]],

       [[15, 21],
        [17, 11],
        [ 1,  8]],

       [[16,  2],
        [21,  2],
        [ 7, 17]]], dtype=int32)

#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [232]:
array_normal= np.random.randint(1,24, (3,2,4))
print(array_normal)
np.transpose(array_normal, (2, 0, 1 )) 

[[[13 17 15 14]
  [ 6 14  7 23]]

 [[18 12 12 21]
  [ 9 21 19 13]]

 [[11 15 21 12]
  [11  3 21 19]]]


array([[[13,  6],
        [18,  9],
        [11, 11]],

       [[17, 14],
        [12, 21],
        [15,  3]],

       [[15,  7],
        [12, 19],
        [21, 21]],

       [[14, 23],
        [21, 13],
        [12, 19]]], dtype=int32)

#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [264]:
array_normal= np.random.randint(-10,11, (3,4,5))
array_vacio= np.empty((3,4,5), dtype= '<U100')
mediana= np.median(array_normal) 
max= np.max(array_normal)
min= np.min(array_normal) 

 
where_igual= np.where( array_normal == mediana )
where_menor= np.where( (array_normal < mediana) & (array_normal > min) )
where_mayor= np.where( (array_normal > mediana) & (array_normal < max))
where_max= np.where( array_normal == max )
where_min= np.where( array_normal == min )
                           #Tengo los índices del array normal

             #Tengo los números correspondientes

array_vacio[ where_igual] = "M"
array_vacio[where_mayor]= "X"
array_vacio[where_menor] = "Y"
array_vacio[where_max] = "MAX"
array_vacio[where_min]= "MIN"

print(array_normal)
print(array_vacio)


[[[  2   1   0  -6  -7]
  [  0   0  -4   3   6]
  [-10   2  -7   0   5]
  [  7  -8  -1  -9   0]]

 [[  6   5  -4   0   8]
  [ 10  -5  -7  -6   6]
  [ -5  -1  -1  -2   2]
  [ -7  -4  10  -2  10]]

 [[  6 -10   5  -8  -3]
  [  3  -9   2   8   4]
  [ -5   0   3 -10   6]
  [ -4   1  -1   4   6]]]
[[['X' 'X' 'M' 'Y' 'Y']
  ['M' 'M' 'Y' 'X' 'X']
  ['MIN' 'X' 'Y' 'M' 'X']
  ['X' 'Y' 'Y' 'Y' 'M']]

 [['X' 'X' 'Y' 'M' 'X']
  ['MAX' 'Y' 'Y' 'Y' 'X']
  ['Y' 'Y' 'Y' 'Y' 'X']
  ['Y' 'Y' 'MAX' 'Y' 'MAX']]

 [['X' 'MIN' 'X' 'Y' 'Y']
  ['X' 'Y' 'X' 'X' 'X']
  ['Y' 'M' 'X' 'MIN' 'X']
  ['Y' 'X' 'Y' 'X' 'X']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [358]:


array_normal= np.random.randint(1,20, (4,4))
print(array_normal)

coincide = False

for i in range(4):   #i fila
    for j in range(4):    #j columna
        fila_columna_iguales = True
        for k in range(4):      #k es el índice de los elementos
            if array_normal[i][k] != array_normal[k][j]:
                fila_columna_iguales = False
                break        #Salimos del bucle si encontramos una diferencia 
                             
        if fila_columna_iguales:
            print(f"La fila {i+1} es igual a la columna {j+1}.")
            coincide = True
            break
if not coincide:
    print("No hay ninguna fila que coincida exactamente con una columna.")


[[ 1  2  4 16]
 [11 19  7  4]
 [ 2 10 13  9]
 [14  6 19 16]]
No hay ninguna fila que coincida exactamente con una columna.
